CREATE TABLE users(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
type TEXT NOT NULL,
CHECK(type IN ('admin','normal'))
);

CREATE TABLE article_categories(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL
);

CREATE TABLE articles(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL,
content TEXT NOT NULL,
user_id INT NOT NULL,
category_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (category_id) REFERENCES article_categories(id)
);

CREATE TABLE comments(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
content TEXT NOT NULL,
user_id INT NOT NULL ,
article_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (article_id) REFERENCES articles(id)
);

sql_practice=# select * from articles
sql_practice-# ;
 id | title | content | user_id | category_id
----+-------+---------+---------+-------------
  1 | a1    | intro   |       1 |           1
  2 | a2    | intro   |       1 |           1
  3 | a3    | intro   |       2 |           1
  4 | a4    | intro   |       2 |           1
(4 rows)


sql_practice=# select * from users;
 id |  name  |  type
----+--------+--------
  1 | user3  | normal
  2 | admin1 | admin
  3 | u3     | normal
(3 rows)


sql_practice=# select * from comments;
 id | content | user_id | article_id
----+---------+---------+------------
  1 | c1      |       1 |          1
  2 | c2      |       2 |          1
  3 | c3      |       3 |          2
  4 | c4      |       3 |          4
  5 | c5      |       3 |          4
  6 | c6      |       1 |          4
(6 rows)


sql_practice=# SELECT articles.title
sql_practice-# FROM articles
sql_practice-# JOIN users
sql_practice-# ON articles.user_id = users.id
sql_practice-# where users.name = 'user3';
 title
-------
 a1
 a2
(2 rows)

sql_practice=# \set find_name 'user3'
sql_practice=# SELECT articles.title
sql_practice-# FROM articles
sql_practice-# JOIN users
sql_practice-# ON articles.user_id = users.id
sql_practice-# where users.name = :'find_name';
 title
-------
 a1
 a2
(2 rows)

sql_practice=# SELECT a.title , c.id AS comment_id
sql_practice-# FROM articles a
sql_practice-# LEFT JOIN comments c
sql_practice-# ON a.id = c.article_id
sql_practice-# WHERE a.id IN (
sql_practice(# SELECT articles.id
sql_practice(# FROM articles
sql_practice(# JOIN users
sql_practice(# ON articles.user_id = users.id
sql_practice(# where users.name = 'user3'
sql_practice(# );
 title | comment_id
-------+------------
 a1    |          1
 a1    |          2
 a2    |          3
(3 rows)

sql_practice=# SELECT a.title, c.id AS comment_id
sql_practice-# FROM articles a
sql_practice-# LEFT JOIN comments c
sql_practice-# ON c.article_id = a.id
sql_practice-# JOIN users u
sql_practice-# ON a.user_id = u.id
sql_practice-# where u.name = 'user3';
 title | comment_id
-------+------------
 a1    |          1
 a1    |          2
 a2    |          3
(3 rows)

sql_practice=# SELECT a.*
sql_practice-# FROM articles a
sql_practice-# LEFT JOIN comments c
sql_practice-# ON a.id = c.article_id
sql_practice-# WHERE c.id IS NULL;
 id | title | content | user_id | category_id
----+-------+---------+---------+-------------
  3 | a3    | intro   |       2 |           1
(1 row)

sql_practice=# SELECT *
sql_practice-# FROM articles
sql_practice-# WHERE id NOT IN (
sql_practice(# SELECT article_id
sql_practice(# FROM comments
sql_practice(# );
 id | title | content | user_id | category_id
----+-------+---------+---------+-------------
  3 | a3    | intro   |       2 |           1
(1 row)

sql_practice=# SELECT a.title, COUNT(c.id) AS comments_count
sql_practice-# FROM articles a
sql_practice-# LEFT JOIN comments c
sql_practice-# ON c.article_id = a.id
sql_practice-# GROUP BY a.id
sql_practice-# ORDER BY comments_count DESC
sql_practice-# LIMIT 1;
 title | comments_count
-------+----------------
 a4    |              3
(1 row)

sql_practice=# SELECT a.id, a.title
sql_practice-# FROM articles a
sql_practice-# LEFT JOIN comments c
sql_practice-# ON a.id = c.article_id
sql_practice-# GROUP BY a.id,a.title
sql_practice-# HAVING COUNT(c.user_id) = COUNT(DISTINCT c.user_id);
 id | title
----+-------
  1 | a1
  2 | a2
  3 | a3
(3 rows)
